### ISSUE TITLE
TLD Voting

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/GTNewHorizons.github.io#1]
@GTNewHorizons/owners 
I'm considering renting an affordable domain name for our site (should be live this week).
Here are some options which are currently available, feel free to suggest more!

Pick one that stands out or sounds nice to you (if any).
Here is some if the name is to be kept intact:

newhorizons.eu
newhorizons.xyz
newhorizons.website
newhorizons.link
newhorizons.rocks
newhorizons.com.de
newhorizons.re
newhorizons.pm
newhorizons.tf
newhorizons.wf
newhorizons.yt

Should we go with the theme and go for the full name *GregTech: New Horizons* we have more traditional options available:

GTNewHorizons.com
GTNewHorizons.net
GTNewHorizons.org
GTNewHorizons.info
GTNewHorizons.us
GTNewHorizons.space
GTNewHorizons.in
...and other ridiculous names like GTNewHorizons.party and GTNewHorizons.work, GTNewHorizons.sexy, etc.

Alternatively something like NewHorizonsModPack.com or combination of the above.
.xyz and .website (and other uncommon TLDs like .rocks) and surprisingly .eu are the cheapest of the lot.

Add the forum to the domain under newhorizons.xyz/forum or newhorizons.xyz/community for bonus points.

**Comment by Namikon** [comment]
You want to rent a Domain? Will it be just a domain or one with attached webspace?

**Comment by Teteros** [comment]
Since Github provides hosting, I'm thinking domain only.
If I was to pick a host, I'd go for a VPS like DigitalOcean or GTComm.

**Comment by Namikon** [comment]
Forum on that Domain should not a big deal, as long as you have access to the DNS records. If it's a VPS, then we could also consider moving the forum. But MyBB has pretty low requirements, so it should run everywhere. About the Domains: last time I checked, special domain names like .info, .us, etc. aren't cheap, at least if I wan't to buy them for my Server... But that could be also a Germoney thing...

**Comment by Teteros** [comment]
Most of ones I listed are under ~5 euro/year so its not too bad. I've applied for the github student pack as well which may make things cheaper. DNS records/management will be included. (I need it for the CNAME file to work anyways)

Hmm... So, should it be GTNewhorizons or NewHorizons...

**Comment by Namikon** [comment]
I'd vote for GTNewhorizons, to have the same name on every platform

**Comment by Teteros** [comment]
+1, makes it more SEO-friendly as well.  A full name like: *GregTech: New horizons* makes sense as well.

**Comment by Dream-Master** [comment]
Maybe GTNewHorizons.space

**Comment by Teteros** [comment]
Since GTNewHorizons.com is available, I think I'll pick it over the general TLDs for user familiarity/friendliness.
