### ISSUE TITLE
Forum offline

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/GTNewHorizons.github.io#2]
The forum is offline until the DNS records have been updated.
New address: http://forum.gtnewhorizons.com
I still have to make a few changes to the backend before it can be used again, but you can already bookmark the link

**Comment by Dream-Master** [comment]
OK

**Comment by Namikon** [comment]
@Teteros 
Please check your DNS config.
The A-Record for forum.gtnewhorizons.com is still pointing to 104.27.163.107.

**Comment by Teteros** [comment]
Cloudflare is just being slow...
![2015-06-12-121746_956x260_scrot](https://cloud.githubusercontent.com/assets/5067989/8129096/85853d68-10fd-11e5-9682-cecb33f743c1.png)

**Comment by Teteros** [comment]
Seems 104.27.163.107 is Cloudflare's IP.
After disabling it for the forum subdomain, it points to 5.9.133.25 directly.

Though 5.9.133.25 is still the "It Works!" page?

**Comment by Namikon** [comment]
you can remove the www.forum. entry. Just forum. is enough.
Oh and by the way, forum back online :)

**Comment by Namikon** [comment]
Shht, MyBB has a neat portal function too:
http://forum.gtnewhorizons.com/portal.php
totally worth the try :P

**Comment by Dream-Master** [comment]
Cant log in in the Forum any more

**Comment by Namikon** [comment]
Forgot your password? Works for me.. Front and Backend oO

**Comment by Dream-Master** [comment]
Maybe something with cookies. I put my Password inside manually in and it works

**Comment by Dream-Master** [comment]
You come inside the TS?

**Comment by Namikon** [comment]
Ah, yes. The cookie domain has changed, obviously. So if you have issues logging in, clear your browser cache (Ctrl+F5 should be enough)
