### ISSUE TITLE
Can't finish BetterQuesting's mission on server

### ISSUE THREAD

**Issue by waitLH** [GTNewHorizons/GTNewHorizons.github.io#3]
I can't finish BetterQuesting's mission when i play gt new horizons on my thermos server,gt new horizons' version is latest 1.4.0.1

**Comment by Dream-Master** [comment]
@waitLH a bit more details/infos or pics would be nice.

**Comment by waitLH** [comment]
@Dream-Master I download the modpack on curse,and i copy 'mods' 'config' 'scripts' into server and delete all mods what can't instal on server,than i go into the server to test,i can play in server but can't finish BetterQuesting's mission,when i got 16 drit i can see the center of the screen prompts，but than i open the book,i saw the page of first mission 'Your first night' as before,i can't get the reward.I didn't increase any others mods.

**Comment by Dream-Master** [comment]
@waitLH try 
/bq_admin default load

If this not help make a vide for me that i understand the issue here.

**Comment by Dream-Master** [comment]
@waitLH Can you post it on the right repo please i dont see it we are one the wrong one.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues
